### ISSUE TITLE
Use date-picker or incremental date fields

### ISSUE THREAD

**Issue by victorlin** [foodaddy/food-baby#10]
Date must be in a [strict format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). UI/UX-wise we should ensure the user doesn't have to type the date in the exact format.

**Comment by alaingarcia** [comment]
Added this on date-picker branch.
Used <input type="datetime-local">

Supported on Edge, Chrome, and Opera.
